"""
Card Processor  —  Step 2 of the Delivery Pipeline
====================================================
Takes a raw feature one-liner from the Trello backlog and uses Claude
to produce a proper Agile card with:
  • User Story  (As a … I want … So that …)
  • Acceptance Criteria  (Given / When / Then scenarios)
  • Priority  (High / Medium / Low)
  • Test scope  (what areas need automation coverage)

The formatted output is written back to the Trello card description
and the card is moved from "Iteration Backlog" → "Ready for Dev".

Usage (CLI):
    python -m pipeline.card_processor --card <TRELLO_CARD_ID>
    python -m pipeline.card_processor --list "Iteration Backlog"   # process all
"""
import argparse
import logging
import sys
from textwrap import dedent

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage

import config
from pipeline.trello_client import TrelloClient, TrelloCard

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

AC_WRITER_PROMPT = dedent("""\
    You are a senior QA engineer and product owner for the FedEx Shopify App
    built by PluginHive. Your job is to turn raw feature requests into
    well-structured Agile cards.

    Given the raw feature request below, produce:

    ## User Story
    As a [type of user], I want [goal], so that [benefit].

    ## Acceptance Criteria
    List each scenario in Given / When / Then format.
    Cover: happy path, edge cases, error states.

    ## Priority
    High / Medium / Low — justify in one sentence.

    ## Test Scope
    List the app sections and automation files that will need coverage.
    Reference existing test areas: Single Label, Rate Domestic/International,
    Label Domestic/International, Orders Grid, Settings, Pickup,
    Return Labels, Notifications, Print Settings, Locations, Bulk Orders.

    ## Out of Scope
    What this story explicitly does NOT cover.

    ---
    Raw feature request:
    {raw_request}
    ---

    Respond with clean markdown. No preamble.
""")


# ---------------------------------------------------------------------------
# Claude helper
# ---------------------------------------------------------------------------

def _get_claude(model: str | None = None) -> ChatAnthropic:
    if not config.ANTHROPIC_API_KEY:
        raise RuntimeError("ANTHROPIC_API_KEY not set in .env")
    return ChatAnthropic(
        model=model or config.CLAUDE_HAIKU_MODEL,   # haiku — fast + cheap
        api_key=config.ANTHROPIC_API_KEY,
        temperature=0.2,
        max_tokens=2048,
    )


def generate_acceptance_criteria(raw_request: str, model: str | None = None) -> str:
    """
    Send a raw feature description to Claude and return the formatted
    User Story + Acceptance Criteria markdown.
    """
    claude = _get_claude(model)
    prompt = AC_WRITER_PROMPT.format(raw_request=raw_request.strip())
    response = claude.invoke([HumanMessage(content=prompt)])
    return response.content.strip()


# ---------------------------------------------------------------------------
# Pipeline step
# ---------------------------------------------------------------------------

def process_card(
    card: TrelloCard,
    trello: TrelloClient,
    move_to: str = "Ready for Dev",
    dry_run: bool = False,
) -> str:
    """
    Process a single Trello card:
    1. Generate AC from card name + existing description
    2. Write AC back to the card description
    3. Add '✅ AC Written' comment
    4. Move card to `move_to` list

    Returns the generated AC markdown.
    """
    raw = f"{card.name}\n\n{card.desc}".strip()
    logger.info("Processing card: %s", card.name)

    ac_markdown = generate_acceptance_criteria(raw)
    logger.info("AC generated (%d chars)", len(ac_markdown))

    if dry_run:
        logger.info("[DRY RUN] Would update card %s", card.id)
        return ac_markdown

    # Write back to card
    trello.update_card_description(card.id, ac_markdown)
    trello.add_comment(
        card.id,
        "🤖 **Card Processor** — Acceptance criteria generated by Claude. "
        "Please review before moving to development."
    )

    # Move to next list
    try:
        trello.move_card_to_list(card.id, move_to)
        logger.info("Moved card to '%s'", move_to)
    except ValueError as e:
        logger.warning("Could not move card: %s", e)

    return ac_markdown


def process_backlog(
    list_name: str = "Iteration Backlog",
    move_to: str = "Ready for Dev",
    dry_run: bool = False,
) -> list[dict]:
    """
    Process all cards in the backlog list.
    Returns list of {card_id, card_name, ac} dicts.
    """
    trello = TrelloClient()
    cards = trello.get_backlog_cards(list_name)
    if not cards:
        logger.warning("No cards found in '%s'", list_name)
        return []

    results = []
    for card in cards:
        try:
            ac = process_card(card, trello, move_to=move_to, dry_run=dry_run)
            results.append({"card_id": card.id, "card_name": card.name, "ac": ac})
        except Exception:
            logger.exception("Failed to process card %s", card.id)

    logger.info("Processed %d / %d cards", len(results), len(cards))
    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

    parser = argparse.ArgumentParser(description="Generate acceptance criteria for Trello cards")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--card", metavar="CARD_ID", help="Process a single card by ID")
    group.add_argument("--list", metavar="LIST_NAME", default="Iteration Backlog",
                       help="Process all cards in a list (default: 'Iteration Backlog')")
    parser.add_argument("--move-to", default="Ready for Dev",
                        help="Move processed cards to this list (default: 'Ready for Dev')")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print AC without writing to Trello")
    args = parser.parse_args()

    if args.card:
        trello = TrelloClient()
        card = trello.get_card(args.card)
        ac = process_card(card, trello, move_to=args.move_to, dry_run=args.dry_run)
        print("\n" + "=" * 60)
        print(ac)
    else:
        results = process_backlog(
            list_name=args.list,
            move_to=args.move_to,
            dry_run=args.dry_run,
        )
        for r in results:
            print(f"\n{'=' * 60}")
            print(f"Card: {r['card_name']}")
            print(r["ac"])
